### ISSUE TITLE
crash happened randomly during game

### ISSUE THREAD

**Issue by Chuunkyz** [Safrodev/Archon#1]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2/14/22, 8:20 PM
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "dev.onyxstudios.cca.api.v3.component.ComponentProvider.getComponentContainer()" because "provider" is null
	at dev.onyxstudios.cca.api.v3.component.ComponentKey.get(ComponentKey.java:83)
	at safro.archon.util.ArchonUtil.get(ArchonUtil.java:25)
	at net.minecraft.client.gui.hud.InGameHud.handler$zjl000$render(InGameHud:3543)
	at net.minecraft.client.gui.hud.InGameHud.render(InGameHud:416)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:856)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1117)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:733)
	at net.minecraft.client.main.Main.main(Main:238)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dev.onyxstudios.cca.api.v3.component.ComponentKey.get(ComponentKey.java:83)
	at safro.archon.util.ArchonUtil.get(ArchonUtil.java:25)
	at net.minecraft.class_329.handler$zjl000$render(class_329.java:3543)
	at net.minecraft.class_329.method_1753(class_329.java:416)

-- Affected level --
Details:
	All players: 1 total; [class_746['chuunkyz__'/110, l='ClientLevel', x=-3579.79, y=69.00, z=2795.49]]
	Chunk stats: 1024, 708
	Level dimension: minecraft:overworld
	Level spawn location: World: (-17,194,-64), Section: (at 15,2,0 in -2,12,-4; chunk contains blocks -32,-64,-64 to -17,319,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 14076 game time, 14076 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Safrodev** [comment]
Strange, I'll take a look soon

**Comment by Safrodev** [comment]
I believe I found a fix, but it'll take me a bit to release it as I have some new content planned

**Comment by Safrodev** [comment]
Fixed as of v0.2.0
