### ISSUE TITLE
Ancient Scrolls not working

### ISSUE THREAD

**Issue by lnSaine** [Safrodev/Archon#6]
Tried using the Ancient Scrolls (Capacity and Removal). Capacity says a scroll is already in use and the Removal doesn't say anything. After checking my mana regen, It seems to regenerate around 2 per second. Which is strange since I haven't used the Accelerate scroll. 

![Ancient Scrolls](https://user-images.githubusercontent.com/89215500/165417396-c1a8161d-0722-42ba-8929-e069eaecd296.JPG)

here is my mod list:

[✔️] appleskin-fabric-mc1.18.2-2.4.0
  [✔️] architectury-4.1.32
  [✔️] archon-0.2.3
  [✔️] backpackmod-1.18.2-3.1.1
  [✔️] balm-fabric-3.0.0+0
  [✔️] Botania-1.18.2-431-FABRIC
  [✔️] cc-restitched-1.100.5
  [✔️] chisel-1.4.5+1.18.x
  [✔️] cloth-config-6.2.57-fabric
  [✔️] ColoredLamps-0.1
  [✔️] Controlling-fabric-1.18.2-9.0+19
  [✔️] conveyor-belts-1.5
  [✔️] craftingtweaks-fabric-1.18-13.0.0
  [✔️] denseores-1.2.2+1.18.2
  [✔️] fabric-api-0.50.0+1.18.2
  [✔️] fabric-language-kotlin-1.7.1+kotlin.1.6.10
  [✔️] geckolib-fabric-1.18.2-3.0.35
  [✔️] HWGMod-1.18.2-1.1.5
  [✔️] immersive-portals-1.3.6-mc1.18.2-fabric
  [✔️] lunade-copper-pipe-r1.9
  [✔️] megane-7.4.0
  [✔️] mobscarecrow-1.2.2
  [✔️] modmenu-3.0.1
  [✔️] MouseTweaks-fabric-mc1.18-2.22
  [✔️] ngv-1.2.0
  [✔️] omnihopper-1.1.0
  [✔️] Patchouli-1.18.2-67-FABRIC
  [✔️] phosphor-fabric-mc1.18.x-0.8.1
  [✔️] Rain-Growth
  [✔️] RebornCore-5.2.0-beta.2
  [✔️] RoughlyEnoughItems-8.1.449
  [✔️] TechReborn-5.2.0-beta.2
  [✔️] trinkets-3.3.0
  [✔️] waystones-fabric-1.18.2-10.0.0
  [✔️] WI-Zoom-1.3-MC1.18.2
  [✔️] wthit-fabric-4.8.1
  [✔️] Xaeros_Minimap_22.5.0_Fabric_1.18.2
  [✔️] XaerosWorldMap_1.20.6_Fabric_1.18.2
  [✔️] youre-in-grave-danger-1.3.1

**Comment by Safrodev** [comment]
Very strange, I will try to recreate this issue.
Two questions:
- Are you 100% you haven’t used any other scroll?
- Are you playing on a server or singleplayer?

**Comment by lnSaine** [comment]
- I'm 100% certain, only found one capacity scroll when I found this bug out.
-I'm playing on a server, works in survival.

**Comment by funnykeyboardsymbols** [comment]
Also having this issue on both server and singleplayer. Using scroll of removal gives the following console error on a server:
`[08:51:37 ERROR] [Server thread]: [PacketUtils] Failed to handle packet net.minecraft.class_2886@3fa42f63, suppressing error
java.lang.StringIndexOutOfBoundsException: begin 0, end 1, length 0
        at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
        at java.lang.String.checkBoundsBeginEnd(String.java:4604) ~[?:?]
        at java.lang.String.substring(String.java:2707) ~[?:?]
        at safro.archon.item.RemovalScrollItem.use(RemovalScrollItem.java:30) ~[archon-0.2.4.jar:?]
        at net.minecraft.item.ItemStack.use(ItemStack:262) ~[?:?]
        at net.minecraft.server.network.ServerPlayerInteractionManager.interactItem(ServerPlayerInteractionManager:291) ~[?:?]
        at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractItem(ServerPlayNetworkHandler:1117) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractItemC2SPacket.apply(PlayerInteractItemC2SPacket:25) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractItemC2SPacket.apply(PlayerInteractItemC2SPacket:7) ~[?:?]
        at net.minecraft.network.NetworkThreadUtils.lambda$ensureRunningOnSameThread$0(NetworkThreadUtils:22) ~[?:?]
        at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
        at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) ~[?:?]
        at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:808) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:165) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
        at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:790) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:784) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:140) ~[?:?]
        at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:769) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:701) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

Modlist attached.
[mods.txt](https://github.com/Safrodev/Archon/files/8785337/mods.txt)
`

**Comment by Safrodev** [comment]
Sorry that it's been a while, but this issue should be fixed in v0.3.0
